### ISSUE TITLE
Travis CI: fails on running e2e tests

### ISSUE THREAD

**Issue by AlexPikalov** [AlexPikalov/cdrs#198]
Travis CI fails on running e2e tests despite locally tests work fine.
Simple re-run a job which was "green" makes it "red".

Log investigation shows that it may be Cassandra run by Travis issue:

```
INFO  10:16:41 Initializing system.schema_aggregates
INFO  10:16:41 Not submitting build tasks for views in keyspace system as storage service is not initialized
Exception (java.lang.AbstractMethodError) encountered during startup: org.apache.cassandra.utils.JMXServerUtils$Exporter.exportObject(Ljava/rmi/Remote;ILjava/rmi/server/RMIClientSocketFactory;Ljava/rmi/server/RMIServerSocketFactory;Lsun/misc/ObjectInputFilter;)Ljava/rmi/Remote;
java.lang.AbstractMethodError: org.apache.cassandra.utils.JMXServerUtils$Exporter.exportObject(Ljava/rmi/Remote;ILjava/rmi/server/RMIClientSocketFactory;Ljava/rmi/server/RMIServerSocketFactory;Lsun/misc/ObjectInputFilter;)Ljava/rmi/Remote;
	at javax.management.remote.rmi.RMIJRMPServerImpl.export(RMIJRMPServerImpl.java:150)
	at javax.management.remote.rmi.RMIJRMPServerImpl.export(RMIJRMPServerImpl.java:135)
	at javax.management.remote.rmi.RMIConnectorServer.start(RMIConnectorServer.java:405)
	at org.apache.cassandra.utils.JMXServerUtils.createJMXServer(JMXServerUtils.java:106)
	at org.apache.cassandra.service.CassandraDaemon.maybeInitJmx(CassandraDaemon.java:145)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:219)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:601)
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:730)
```

**Comment by AlexPikalov** [comment]
Related to http://mail-archives.apache.org/mod_mbox/cassandra-user/201801.mbox/%3CCABinuxcubqObxT4DWOA9ga=xT6jFy+LWod73LPM5=Sup6o+Bkw@mail.gmail.com%3E

Affects: #196, #199

**Comment by AlexPikalov** [comment]
Blocked by https://issues.apache.org/jira/browse/CASSANDRA-14173

**Comment by AlexPikalov** [comment]
E2E tests are disabled on travis CI as of now

**Comment by AlexPikalov** [comment]
UPD: Cassandra 3.11.2 should have the fix. According to [comments](https://issues.apache.org/jira/browse/CASSANDRA-14173?focusedCommentId=16349998&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16349998) the patch will be released soon.

**Comment by AlexPikalov** [comment]
Seems Cassandra 3.11.2 (which is compatible with latest JAVA) was released so I hope to return back e2e to our CI very soon
